name: C++ CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Initialize submodules if using them

    - name: Install C++ Compiler and Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev

    - name: Install CMake and Ninja
      run: |
        sudo apt-get install -y cmake ninja-build

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja

    - name: Configure CMake
      run: |
        rm -rf build/                  # Ensure a clean build directory
        cmake -S . -B build -G Ninja

    - name: Build with CMake
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure
